site_name: Game Dev Kit
site_url: https://game-dev-kit.github.io/
plugins:
  - search:
  - multirepo:

nav:
  - Home: 'index.md'
  - Toolkits:
    - 3D avatar creation: '!import https://github.com/game-dev-kit/3D-avatar-creation?branch=main'
    - Codeless3D: '!import https://github.com/game-dev-kit/Codeless3D?branch=main'
theme: mkdocs
copyright: Copyright &copy; 2023 game-dev-kit